/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SmarterMonitor_controller_SystemController */

#ifndef _Included_SmarterMonitor_controller_SystemController
#define _Included_SmarterMonitor_controller_SystemController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SmarterMonitor_controller_SystemController
 * Method:    killProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SmarterMonitor_controller_SystemController_killProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     SmarterMonitor_controller_SystemController
 * Method:    getallprocesses
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SmarterMonitor_controller_SystemController_getallprocesses
  (JNIEnv *, jclass);

/*
 * Class:     SmarterMonitor_controller_SystemController
 * Method:    getallpids
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SmarterMonitor_controller_SystemController_getallpids
  (JNIEnv *, jclass);

/*
 * Class:     SmarterMonitor_controller_SystemController
 * Method:    getProcInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SmarterMonitor_controller_SystemController_getProcInfo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
